<style>
body {
    font-family: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #454e59;
    background-color: #003f6a;
}
</style>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 </head>

<body>
<div class="row">
<?php
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) {
     echo '<div class="help-block animation-slideUp" style="color:#de815c;padding-left:200px;">';
 ?>
<?php
    foreach ($flashMessage as $msg){
        foreach ($msg as $type => $message) {
               echo $message ;
           }
         }
    echo '</div>';     
     }
 ?>
</div>
 <!-- Login Container -->
<div id="login-container">
    <!-- Login Header -->
    <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
         <img src="/img/logo2.png" /><!--<i class="fa fa-cube"></i> <strong>Welcome to Dental Admin</strong>-->
    </h1>
    <!-- END Login Header -->

    <!-- Login Block -->
    <div class="block animation-fadeInQuickInv">
        <!-- Login Title -->
        <div class="block-title">
            <div class="block-options pull-right">
                <a href="<?php if($frontcheckid==1){  ?>/forgetpass <?php }else{ ?>/adminforgetpass <?php } ?>" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="Forgot your password?"><i class="fa fa-exclamation-circle"></i>
                </a>
                
                <?php 
                if($frontcheckid==1){
                ?>
                <a href="/register" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="Create new account"><i class="fa fa-plus"></i></a>
                <?php
                }
                ?>

              <!--  <a href="page_ready_register.php" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="Create new account"><i class="fa fa-plus"></i></a>-->
            </div>
            <h2>Please Login</h2>
        </div>
        <!-- END Login Title -->

        









        <!-- Login Form -->
  
        <form id="form-login" action="" name="loginForm" method="post" class="form-horizontal">
            <div class="form-group">
                <div class="col-xs-12">

                    <input type="email" id="login-email" name="email" class="form-control" placeholder="Your email..">

                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">

                    <input type="password" id="login-password" name="password" class="form-control" placeholder="Your password..">
                
                </div>
            </div>
            <div class="form-group form-actions">
                <div class="col-xs-8">
                    <!--<label class="csscheckbox csscheckbox-primary">
                        <input type="checkbox" id="login-remember-me" name="login-remember-me">
                        <span></span>
                    </label>
                    Remember Me?-->
                </div>
                <div class="col-xs-12 text-right">
					<button type="reset" class="btn btn-effect-ripple btn-success" onclick="javascript: window.location.assign('/')">Home</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <button type="submit" class="btn btn-effect-ripple btn-sm btn-primary"><i class="fa fa-check"></i> Let's Go</button>
                </div>
            </div>
        </form>
        <!-- END Login Form -->
    </div>
    <!-- END Login Block -->

    <!-- Footer -->
    <footer class="text-muted text-center animation-pullUp">
        <!--<small><span id="year-copy"></span> &copy; <a href="http://goo.gl/RcsdAh" target="_blank"><?php echo $template['name'] . ' ' . $template['version']; ?></a></small>-->
    </footer>
    <!-- END Footer -->
</div>
<!-- END Login Container -->

 
    

</body>

</html>
<!-- Load and execute javascript code used only in this page -->
<script src="js/pages/readyLogin.js"></script>
<script>$(function(){ ReadyLogin.init(); });</script>
