<style>
body {
    font-family: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
    color: #454e59;
    background-color: #003f6a;
}
</style>
<?php
$specialist_arr[1] = 'Dentist';
$specialist_arr[2] = 'Pediatric Dentists';
$specialist_arr[3] = 'Other Specialist';

// gender type
$sex[1] = 'Male';
$sex[2] = 'Female';

?>
<!-- Page content -->
<div id="login-container">
    <!-- Forms Components Header -->
    <h1 class="h2 text-light text-center push-top-bottom animation-slideDown">
        <i class="fa fa-plus"></i> <strong>Create Doctor Account</strong>
    </h1>
    <!-- END Forms Components Header -->

    <!-- Form Components Row -->
    <div class="row">
      <?php if($action1==1000) { ?>
            <div class="col-sm-12">
                <!-- Success Alert -->
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><strong>Success</strong></h4>
                    <p>Record added successfully!</p>
                </div>
                <!-- END Success Alert -->
            </div>
<?php }?>
<?php if($exists==1) { ?>
  <div class="col-md-12">
    <!-- Danger Alert -->
    <div class="alert alert-danger alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">x</button>
      <h4><strong>Error</strong></h4>
      <p>Username alredy exists</p>
    </div>
    <!-- END Danger Alert -->
  </div>
<?php }?>
    <div class="block animation-fadeInQuickInv">
        <!-- Register Title -->
        <div class="block-title">
            <div class="block-options pull-right">
                <a href="/admin/1" class="btn btn-effect-ripple btn-primary" data-toggle="tooltip" data-placement="left" title="Back to login"><i class="fa fa-user"></i></a>
            </div>
            <h2>Register</h2>
        </div>

                <!-- General Elements Content -->
        <form id="form-register" action="/register" method="post" class="form-horizontal">
            <div class="form-group">
                <label class="col-md-3 control-label" for="example-text-input">First Name</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_firstname" name="doc_firstname" class="form-control" placeholder="First Name" value="<?php echo $_POST['doc_firstname'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Last Name</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_lastname" name="doc_lastname" class="form-control" placeholder="last Name" value="<?php echo $_POST['doc_lastname'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Email</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_email" name="doc_email" class="form-control" placeholder="Email" value="<?php echo $_POST['doc_email'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Phone</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_phone" name="doc_phone" class="form-control" placeholder="Phone" value="<?php echo $_POST['doc_phone'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Phone 2</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_phone2" name="doc_phone2" class="form-control" placeholder="Phone 2" value="<?php echo $_POST['doc_phone2'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-textarea-input">Address</label>
                        <div class="col-md-9">
                            <textarea id="doc_address" name="doc_address" rows="7" class="form-control" placeholder="Address, Street, City, State"><?php echo $_POST['doc_address'];?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Zip</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_zip" name="doc_zip" class="form-control" placeholder="Zip" value="<?php echo $_POST['doc_zip'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Gender</label>
                        <div class="col-md-6">
                            <select name="doc_sex" id="doc_sex" class="form-control">
                <option value="">-Select-</option>
                <?php foreach($sex as $sex_key=>$sex_val) { 
                  if($sex_key==$_POST['doc_sex']) {
                    $chksex = 'selected="selected"';
                  } else { $chksex = ''; }                
  ?>
                  <option value="<?php echo $sex_key;?>" <?php echo $chksex;?>><?php echo $sex_val;?></option>
                <?php } ?>
              </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Speciality</label>
                        <div class="col-md-6">
                            <select name="doc_speciality" id="doc_speciality" class="form-control">
                <option value="">-Select-</option>
                <?php 
                  foreach($specialist_arr as $skey=>$sval) { $speciality_chked = '';
                  if($skey==$_POST['doc_speciality']) $speciality_chked  = 'selected="selected"';
                ?>
                <option value="<?php echo $skey;?>" <?=$speciality_chked?>><?php echo $sval;?></option>
                <?php }  ?>
              </select> <input type="text" name="doc_speciality_detail" class="form-control" id="doc_speciality_detail" placeholder="Speciality" value="<?php echo $_POST['doc_speciality_detail'];?>" style="display:none;" /> 
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Username</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_username" name="doc_username" class="form-control" placeholder="Username" value="<?php echo $_POST['doc_username'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Password</label>
                        <div class="col-md-6">
                            <input type="password" id="doc_pass" name="doc_pass" class="form-control" placeholder="Password" value="">
                        </div>
                    </div>
          <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-6">
              <input type="password" id="password-verify" name="password-verify" class="form-control" placeholder="Verify Password">
            </div>
          </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">License No.</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_license_no" name="doc_license_no" class="form-control" placeholder="License No." value="<?php echo $_POST['doc_license_no'];?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label" for="example-text-input">Contact Person</label>
                        <div class="col-md-6">
                            <input type="text" id="doc_contact_person" name="doc_contact_person" class="form-control" placeholder="Contact Person" value="<?php echo $_POST['doc_contact_person'];?>">
                        </div>
                    </div>
                    <div class="form-group form-actions">
                        <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-effect-ripple btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
                <!-- END General Elements Content -->
            </div>
        
    </div>
    <!-- END Form Components Row -->
</div>
<!-- END Page Content -->
<!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
<script src="js/vendor/jquery-2.1.4.min.js"></script>
<script src="js/vendor/bootstrap.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/app.js"></script>

<!-- Load and execute javascript code used only in this page -->
<script src="js/pages/readyRegister.js"></script>
<script>$(function(){ ReadyRegister.init();
$('#doc_speciality').change(function(e){
showhide = $("#doc_speciality").val();
if(showhide==3) {
$("#doc_speciality_detail").show();
} else {
$("#doc_speciality_detail").hide();
}
    });
 });</script>
