<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Dental Plan Software</title>

        <meta name="description" content="AppUI Frontend is a Responsive Bootstrap Site Template created by pixelcave and added as a bonus in AppUI Admin Template package">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="/front_img/favicon.png">
        <link rel="apple-touch-icon" href="/front_img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="/front_img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="/front_img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="/front_img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="/front_img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="/front_img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="/front_img/icon152.png" sizes="152x152">
        <link rel="apple-touch-icon" href="/front_img/icon180.png" sizes="180x180">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="/front_css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="/front_css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="/front_css/main.css">

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="/front_css/themes.css">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="/front_js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container" class="boxed">
              <!-- Site Header -->
            <header>
                <div class="container">
                    <div class="site-logo"><a href="/" class="site-logo"><img src="/front_img/logo1.png" alt="Logo"></a></div>
                    <!-- Site Logo -->
                  
                    <!-- END Site Logo -->

                    <!-- Site Navigation -->
                    <nav>
                        <!-- Menu Toggle -->
                        <!-- Toggles menu on small screens -->
                        <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">Menu</a>
                        <!-- END Menu Toggle -->

                        <!-- Main Menu -->
                        <ul class="site-nav">
                             <li>
                                <a href="/" class="active">Home</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/aboutus">About Us</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/features">Features</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/pricing">Pricing</a>
                            </li>
                           <!-- <li>
                                <a href="specialists.html">Specialists</a>
                            </li>-->
                            <li>
                                <a href="/dashboardfront/contact">Contact Us</a>
                            </li>
                         <!--  <li>
                                <a href="javascript:void(0)" class="site-nav-sub"><i class="fa fa-angle-down site-nav-arrow"></i>More</a>
                                <ul>
                                    <li>
                                        <a href="about.html">About Us</a>
                                    </li>
                                    <li>
                                         <a href="faq.html">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                    </li>
                                     <li>
                                        <a href="revenue.html">Potential Revenue</a>
                                    </li>
                                </ul>
                            </li>-->
                            <li>
                                <a href="/admin/1" class="featured">Sign In<i class="fa fa-arrow-right"></i></a>
                            </li>
                        </ul>
                        <!-- END Main Menu -->
                    </nav>
                    <!-- END Site Navigation -->
                </div>
            </header>
            <!-- END Site Header -->

            <!-- Intro -->
            <section class="site-section site-section-top site-section-light themed-background-dark">
                <div class="container">
                    <h1 class="text-center animation-fadeInQuickInv"><strong>We are here if you need help.</strong></h1>
                </div>
            </section>
            <!-- END Intro -->

            <!-- Google Map -->
            <!-- Gmaps.js (initialized in front_js/pages/contact.js), for more examples you can check out http://hpneo.github.io/gmaps/examples.html -->
            <div id="gmap" style="height: 300px;"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3315.9376560548!2d-117.85284854883314!3d33.78810808058375!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80dcd9e6ee17757f%3A0xf8e5787da8ed532a!2s307+E+Chapman+Ave%2C+Orange%2C+CA+92866%2C+USA!5e0!3m2!1sen!2sin!4v1451369848309" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe></div>
            <!-- END Google Map -->

            <!-- Contact -->
            <section class="site-content site-section">
                <div class="container">
                <div align="center" style="line-height:40px;"><strong>Address:</strong> 307 E Chapman Avenue,  Orange CA, 92866<br>
<strong>Phone:</strong> (949) 929-8725<br>
<strong>Support:</strong> Support@DentalPlanSoftware.com<br> 
<strong>Sales:</strong> Sales@DentalPlanSoftware.com<br><br><br>
</div>
                    <div class="row">
                    
                        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 site-block">
                            <form action="/dashboardfront/contact" method="post" id="form-contact">
                                <div class="form-group">
                                    <label for="contact-name">Name</label>
                                    <input type="text" id="contact-name" name="contact-name" class="form-control input-lg" placeholder="Your full name..">
                                </div>
                                <div class="form-group">
                                    <label for="contact-email">Email</label>
                                    <input type="text" id="contact-email" name="contact-email" class="form-control input-lg" placeholder="Your email address..">
                                </div>
                                <div class="form-group">
                                    <label for="contact-message">Message</label>
                                    <textarea id="contact-message" name="contact-message" rows="10" class="form-control input-lg" placeholder="How can we help?"></textarea>
                                </div>
                                <div class="form-group">
                                    <button type="submit"  class="btn btn-lg btn-primary">Send Message</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Contact -->

            <!-- Footer -->
            <footer class="site-footer site-section site-section-light">
                <div class="container">
                    <!-- Footer Links -->
                    <div class="row">
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Company</h4>
                            <ul class="footer-nav ul-breath list-unstyled">
                                <li><a href="/dashboardfront/aboutus">About Us</a></li>
                                <li><a href="/dashboardfront/features">Features</a></li>
                                <li><a href="/dashboardfront/pricing">Pricing</a></li>
                                <li><a href="/dashboardfront/termscondition">Terms &amp; Conditions</a></li>
                                <li><a href="/dashboardfront/privacypolicy">Privacy Policy</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Need support?</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="/dashboardfront/contact"><i class="fa fa-fw fa-book"></i> Contact Us</a></li>
                            </ul>
                            <h4 class="footer-heading">We are social!</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="javascript:void(0)" class="social-facebook" data-toggle="tooltip" title="Like our Facebook page"><i class="fa fa-fw fa-facebook"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-twitter" data-toggle="tooltip" title="Follow us on Twitter"><i class="fa fa-fw fa-twitter"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-google-plus" data-toggle="tooltip" title="Like our Google+ page"><i class="fa fa-fw fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Newsletter</h4>
                            <form action="/dashboardfront/suscribe" method="post" class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="register-email">Your Email</label>
                                    <div class="input-group">
                                        <input type="email" id="register-email" name="register-email" class="form-control" placeholder="Your Email..">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Subscribe</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <h4 class="footer-heading"><a href="/dashboardfront/contact" style="color:#FFC">Check Demo</a></h4>
                            &copy;<em>2016</em> Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://docmate.com/" style="color:#FFC">A1 Healthcare Technologies</a>
                        </div>
                    </div>
                    <!-- END Footer Links -->
                </div>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in front_js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-arrow-up"></i></a>

        <!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
        <script src="/front_js/vendor/jquery-2.1.4.min.js"></script>
        <script src="/front_js/vendor/bootstrap.min.js"></script>
        <script src="/front_js/plugins.js"></script>
        <script src="/front_js/app.js"></script>

        <!-- Google Maps API + Gmaps Plugin, must be loaded in the page you would like to use maps -->
        <script src="//maps.google.com/maps/api/js?sensor=true"></script>
        <script src="/front_js/plugins/gmaps.min.js"></script>

        <!-- Load and execute javascript code used only in this page -->
        <script src="/front_js/pages/contact.js"></script>
        <script>$(function(){ Contact.init(); });</script>
    </body>
</html>

<script>
function sendmessage(){
    window.location.href="/dashboardfront/contact/"+3;
}


</script>
