<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Dental Plan Software</title>

        <meta name="description" content="AppUI Frontend is a Responsive Bootstrap Site Template created by pixelcave and added as a bonus in AppUI Admin Template package">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="/front_img/favicon.png">
        <link rel="apple-touch-icon" href="/front_img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="/front_img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="/front_img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="/front_img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="/front_img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="/front_img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="/front_img/icon152.png" sizes="152x152">
        <link rel="apple-touch-icon" href="/front_img/icon180.png" sizes="180x180">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="/front_css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="/front_css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="/front_css/main.css">

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="/front_css/themes.css">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="/front_js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container" class="boxed">
              <!-- Site Header -->
            <header>
                <div class="container">
                	<div class="site-logo"><a href="/" class="site-logo"><img src="/front_img/logo1.png" alt="Logo"></a></div>
                    <!-- Site Logo -->
                  
                    <!-- END Site Logo -->

                    <!-- Site Navigation -->
                    <nav>
                        <!-- Menu Toggle -->
                        <!-- Toggles menu on small screens -->
                        <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">Menu</a>
                        <!-- END Menu Toggle -->

                        <!-- Main Menu -->
                        <ul class="site-nav">
                            <li>
                                <a href="/" class="active">Home</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/aboutus">About Us</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/features">Features</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/pricing">Pricing</a>
                            </li>
                           <!-- <li>
                                <a href="specialists.html">Specialists</a>
                            </li>-->
                            <li>
                                <a href="/dashboardfront/contact">Contact Us</a>
                            </li>
                         <!--  <li>
                                <a href="javascript:void(0)" class="site-nav-sub"><i class="fa fa-angle-down site-nav-arrow"></i>More</a>
                                <ul>
                                	<li>
                                        <a href="about.html">About Us</a>
                                    </li>
                                  	<li>
                                   		 <a href="faq.html">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                    </li>
                                     <li>
                                        <a href="revenue.html">Potential Revenue</a>
                                    </li>
                                </ul>
                            </li>-->
                            <li>
                                <a href="/admin/1" class="featured">Sign In<i class="fa fa-arrow-right"></i></a>
                            </li>
                        </ul>
                        <!-- END Main Menu -->
                    </nav>
                    <!-- END Site Navigation -->
                </div>
            </header>
            <!-- END Site Header -->

            <!-- Intro -->
            <section class="site-section site-section-top site-section-light themed-background-dark">
                <div class="container">
                    <h1 class="text-center animation-fadeInQuickInv"><strong>The best features in one software.</strong></h1>
                </div>
            </section>
            <!-- END Intro -->

            <!-- Features #1 -->
            <section class="site-content site-section border-bottom">
                <div class="container text-center">
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-danger" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                            <img src="/front_img/web63.png" width="48" height="48"> </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                              <h4 class="site-heading feature-heading"><strong>Patient Portal</strong></h4>
                                <p class="feature-text text-muted">Your patients can login and view their coverage, change plans or add family.  Patients can see how much coverage they have used and what they have left so or the patient dont have to call their insurance company to verify what they have left to use. 
</p>
                          </div>
                      </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-success" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/personal23.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Doctor Dashboard</strong></h4>
                                <p class="feature-text text-muted">Get a full overview of everything that is going on with your practice’s Private Dental Plan.  Dental Plan Software gives you all the information you need all in one place. </p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-info" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="fa fa-book"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Full Analytics</strong></h4>
                                <p class="feature-text text-muted">Get all the numbers of your revenue, patients in each dental plan, accepted or rejected patient referrals and more throughout your own Dental Plan Software account.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Features #1 -->

            <!-- Features #2 -->
            <section class="site-content site-section border-bottom">
                <div class="container text-center">
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-amethyst" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="gi gi-eye_open"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Create Unlimited Plans</strong></h4>
                                <p class="feature-text text-muted">One plan, two plans, three plans or more.  You can have as many plans as you want so your patients can choose what is right for them.</p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-flat" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/money136.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Recurring Billing</strong></h4>
                                <p class="feature-text text-muted">Dental Plan Software pricess the recurring billing for you for all your patients so you dont have to worry about paying fees, setting up merchant accounts etc.</p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-passion" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="gi gi-iphone_shake"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Weekly Payouts</strong></h4>
                                <p class="feature-text text-muted">Receive your recurring revenue straight to your bank account every week.  Since we process billing of your dental plans, we make sure you receive your payout without any hiccups or third parties. 
</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Features #2 -->

            <!-- Features #3 -->
            <section class="site-content site-section border-bottom">
                <div class="container text-center">
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-warning" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/businessmen35.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Patient Management System</strong></h4>
                                <p class="feature-text text-muted">Dental Plan Software manages your patients and plans with top of the line security and algorithms.  You will see all of your statistics of plans and patients all in one place.</p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-info" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/world58.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Specialist Network</strong></h4>
                                <p class="feature-text text-muted">Refer your patients to the top specialists in the Dental Plan Software network.  Specialists are hand chosen and the best in their field. </p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-classy" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/send4.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Email Marketing</strong></h4>
                                <p class="feature-text text-muted">We integrate to your practice management system so you can send mass email marketing to your patients to grow your Private Dental Plan base within your practice.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Features #3 -->

            <!-- Features #4 -->
            <section class="site-content site-section">
                <div class="container text-center">
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-success" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="fa fa-check"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Easily Setup Patients</strong></h4>
                                <p class="feature-text text-muted">Dental Plan Software makes it simple for you to add your patients to your private dental plan.  You can even add family members of your patients and grow your revenue even more. </p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/dollar177.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Manage Your Fee Schedule</strong></h4>
                                <p class="feature-text text-muted">Specialists can create and manage their own fee schedule to stay competitive in the market.  Patients will be able to choose the specialist they like best according to fee schedule and profile.</p>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-social" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/office.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong>Patient ID Cards</strong></h4>
                                <p class="feature-text text-muted">Dental Plan Software automatically emails your private dental plan ID cards to patients the moment you set them up for a plan. This gives you the professional look of an insurance company and gives the patient the warmth of being part of a trusted network.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Features #4 -->

            <!-- Quick Stats -->
            <!--<section class="site-content site-section themed-background-dark">
                <div class="container">
                   
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="counter site-block">
                                <span data-toggle="countTo" data-to="2120" data-after="+"></span>
                                <small>Total Revenue</small>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="counter site-block">
                                <span data-toggle="countTo" data-to="530" data-after="+"></span>
                                <small>Doctors Registered</small>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="counter site-block">
                                <span data-toggle="countTo" data-to="3200" data-after="+"></span>
                                <small>Patient Registered</small>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </section>-->
            <!-- END Quick Stats -->

            <!-- Sign Up Action -->
            <!--<section class="site-content site-section">
                <div class="container">
                    <h2 class="site-heading text-center">Sign up today and receive <strong>30% discount</strong>!</h2>
                    <div class="site-block text-center">
                        <form action="features.html" method="post" class="form-inline" onsubmit="return false;">
                            <div class="form-group">
                                <label class="sr-only" for="register-username">Username</label>
                                <input type="text" id="register-username" name="register-username" class="form-control input-lg" placeholder="Choose a username..">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="register-password">Password</label>
                                <input type="password" id="register-password" name="register-password" class="form-control input-lg" placeholder="..and a password!">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-success">Get Started!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>-->
            <!-- END Sign Up Action -->

            <!-- Footer -->
            <footer class="site-footer site-section site-section-light">
                <div class="container">
                    <!-- Footer Links -->
                    <div class="row">
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Company</h4>
                            <ul class="footer-nav ul-breath list-unstyled">
                                <li><a href="/dashboardfront/aboutus">About Us</a></li>
                                <li><a href="/dashboardfront/features">Features</a></li>
                                <li><a href="/dashboardfront/pricing">Pricing</a></li>
                                <li><a href="/dashboardfront/termscondition">Terms &amp; Conditions</a></li>
                                <li><a href="/dashboardfront/privacypolicy">Privacy Policy</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Need support?</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="/dashboardfront/contact"><i class="fa fa-fw fa-book"></i> Contact Us</a></li>
                            </ul>
                            <h4 class="footer-heading">We are social!</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="javascript:void(0)" class="social-facebook" data-toggle="tooltip" title="Like our Facebook page"><i class="fa fa-fw fa-facebook"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-twitter" data-toggle="tooltip" title="Follow us on Twitter"><i class="fa fa-fw fa-twitter"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-google-plus" data-toggle="tooltip" title="Like our Google+ page"><i class="fa fa-fw fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Newsletter</h4>
                            <form action="/dashboardfront/subscribe" method="post" class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="register-email">Your Email</label>
                                    <div class="input-group">
                                        <input type="email" id="register-email" name="register-email" class="form-control" placeholder="Your Email..">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Subscribe</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <h4 class="footer-heading"><a href="contact.html" style="color:#FFC">Check Demo</a></h4>
                            &copy; <em>2016</em>Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://docmate.com/" style="color:#FFC">A1 Healthcare Technologies</a>
                        </div>
                    </div>
                    <!-- END Footer Links -->
                </div>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in front_js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-arrow-up"></i></a>

        <!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
        <script src="/front_js/vendor/jquery-2.1.4.min.js"></script>
        <script src="/front_js/vendor/bootstrap.min.js"></script>
        <script src="/front_js/plugins.js"></script>
        <script src="/front_js/app.js"></script>
    </body>
</html>
