<!DOCTYPE html>
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <title>Dental Plan Software</title>

        <meta name="description" content="AppUI Frontend is a Responsive Bootstrap Site Template created by pixelcave and added as a bonus in AppUI Admin Template package">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">

        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

        <!-- Icons -->
        <!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
        <link rel="shortcut icon" href="/front_img/favicon.png">
        <link rel="apple-touch-icon" href="/front_img/icon57.png" sizes="57x57">
        <link rel="apple-touch-icon" href="/front_img/icon72.png" sizes="72x72">
        <link rel="apple-touch-icon" href="/front_img/icon76.png" sizes="76x76">
        <link rel="apple-touch-icon" href="/front_img/icon114.png" sizes="114x114">
        <link rel="apple-touch-icon" href="/front_img/icon120.png" sizes="120x120">
        <link rel="apple-touch-icon" href="/front_img/icon144.png" sizes="144x144">
        <link rel="apple-touch-icon" href="/front_img/icon152.png" sizes="152x152">
        <link rel="apple-touch-icon" href="/front_img/icon180.png" sizes="180x180">
        <!-- END Icons -->

        <!-- Stylesheets -->
        <!-- Bootstrap is included in its original form, unaltered -->
        <link rel="stylesheet" href="/front_css/bootstrap.min.css">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="/front_css/plugins.css">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="/front_css/main.css">
                
        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="/front_css/themes.css">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="/front_js/vendor/modernizr-2.8.3.min.js"></script>
    </head>
    <body>
        <!-- Page Container -->
        <!-- In the PHP version you can set the following options from inc/config file -->
        <!-- 'boxed' class for a boxed layout -->
        <div id="page-container" class="boxed">
            <!-- Site Header -->
            <header>
                <div class="container">
                    <div class="site-logo"><a href="/" class="site-logo"><img src="/front_img/logo1.png" alt="Logo"></a></div>
                    <!-- Site Logo -->
                  
                    <!-- END Site Logo -->

                    <!-- Site Navigation -->
                    <nav>
                        <!-- Menu Toggle -->
                        <!-- Toggles menu on small screens -->
                        <a href="javascript:void(0)" class="btn btn-default site-menu-toggle visible-xs visible-sm">Menu</a>
                        <!-- END Menu Toggle -->

                        <!-- Main Menu -->
                        <ul class="site-nav">
                            <li>
                                <a href="/" class="active">Home</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/aboutus">About Us</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/features">Features</a>
                            </li>
                            <li>
                                <a href="/dashboardfront/pricing">Pricing</a>
                            </li>
                           <!-- <li>
                                <a href="specialists.html">Specialists</a>
                            </li>-->
                            <li>
                                <a href="/dashboardfront/contact">Contact Us</a>
                            </li>
                         <!--  <li>
                                <a href="javascript:void(0)" class="site-nav-sub"><i class="fa fa-angle-down site-nav-arrow"></i>More</a>
                                <ul>
                                    <li>
                                        <a href="about.html">About Us</a>
                                    </li>
                                    <li>
                                         <a href="faq.html">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                    </li>
                                     <li>
                                        <a href="revenue.html">Potential Revenue</a>
                                    </li>
                                </ul>
                            </li>-->
                            <li>
                                <a href="/admin/1" class="featured">Sign In<i class="fa fa-arrow-right"></i></a>
                            </li>
                        </ul>
                        <!-- END Main Menu -->
                    </nav>
                    <!-- END Site Navigation -->
                </div>
            </header>
            <!-- END Site Header -->

            <!-- Intro + Action -->
            <section class="site-section site-section-top site-section-light">
                <div class="container">
                    <div class="push text-center">
                        <h1 class="animation-fadeInQuick2Inv"><strong>A powerful software for your Private Dental Plan</strong></h1>
                        <h2 class="text-light-op animation-fadeInQuickInv push-bit"><strong>Recurring revenue every month. </strong></h2>
                        <a href="/dashboardfront/features" class="btn btn-lg btn-success push-right-left"><strong>Features</strong></a>
                        <a href="/dashboardfront/contact" class="btn btn-lg btn-info push-right-left"><strong>Contact Us</strong></a>
                    </div>
                    <div class="site-promo-img visibility-none" data-toggle="animation-appear" data-animation-class="animation-slideUpQuick" data-element-offset="0">
                        <img src="/front_img/placeholders/screenshots/ipad.png" alt="" bor>
                    </div>
                </div>
            </section>
            <!-- END Intro + Action -->

            <!-- Promo Features -->
            <section class="site-content site-section border-bottom">
                <div class="container">
                    <div class="row row-items">
                        <div class="col-sm-4 text-center">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-muted" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/check_mark.png" width="48" height="48">
                            </a>
                            <h2 class="site-heading h4 feature-heading visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-20">
                                <strong>Fully Compliant</strong>
                            </h2>
                        </div>
                        <div class="col-sm-4 text-center">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-muted" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/grow.png" width="48" height="45"> 
                                
                            </a>
                            <h2 class="site-heading h4 feature-heading visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-20">
                                <strong>Grow Your Revenue</strong>
                            </h2>
                        </div>
                        <div class="col-sm-4 text-center">
                            <a href="javascript:void(0)" class="feature visibility-none themed-background-muted" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="fa fa-cogs text-dark"></i>
                            </a>
                            <h2 class="site-heading h4 feature-heading visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-20">
                                <strong>Automated Billing </strong>
                            </h2>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Promo Features -->

            <!-- Promo #1 -->
            <section class="site-section site-content border-bottom overflow-hidden">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 push">
                            <h2 class="site-heading"><strong>Innovative Technology</strong></h2>
                            <p class="feature-text text-muted push">Stop letting insurance companies control your revenue. Built from the ground up with the newest technology to give you the power of having your own Private Dental Plan.</p>
                            <h2 class="site-heading"><strong>Unlimited Plans</strong></h2>
                            <p class="feature-text text-muted">One plan, two plans or three plans.  You can have as many as you want so your patients can choose what is right for them.</p>
                        </div>
                        <div class="col-sm-6 clearfix push">
                            <img src="/front_img/placeholders/screenshots/promo_1.png" alt="" class="img-responsive pull-right visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-200" style="max-width: 450px; margin-right: -130px;">
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Promo #1 -->

            <!-- Quick Stats -->
            <section class="site-content site-section themed-background-dark">
                <div class="container text-center">
                    <!-- Stats Row -->
                    <!-- CountTo (initialized in front_js/app.js), for more examples you can check out https://github.com/mhuggins/jquery-countTo -->
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="/dashboardfront/features" class="feature visibility-none themed-background-amethyst" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="gi gi-eye_open"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Create Unlimited Plans</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">One plan, two plans, three plans or more.  You can have as many plans as you want so your patients can choose what is right for them.</p>-->
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="dashboardfront/features" class="feature visibility-none themed-background-flat" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/money136.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Recurring Billing</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">Dental Plan Software pricess the recurring billing for you for all your patients so you dont have to worry about paying fees, setting up merchant accounts etc.</p>-->
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="/dashboardfront/features" class="feature visibility-none themed-background-passion" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="gi gi-iphone_shake"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Weekly Payouts</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">Receive your recurring revenue straight to your bank account every week.  Since we process billing of your dental plans, we make sure you receive your payout without any hiccups or third parties. 
</p>-->
                            </div>
                        </div>
                    </div>
                    <!-- END Stats Row -->
                </div>
            </section>
            <!-- END Quick Stats -->

            <!-- Promo #2 -->
            <section class="site-section site-content border-bottom overflow-hidden">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-sm-push-6 push">
                            <h2 class="site-heading"><strong>Specialist Network</strong></h2>
                            <p class="feature-text text-muted push">Refer your patients to the top specialists in the Dental Plan Software network.  Specialists are hand chosen and the best in their field.</p>
                            <h2 class="site-heading"><strong>Receive Referrals</strong></h2>
                            <p class="feature-text text-muted">Specialists receive unlimited referrals from the dentists on the Dental Plan Software network.  High amount of referrals received electronically. Instantly.</p>
                        </div>
                        <div class="col-sm-6 col-sm-pull-6 clearfix push">
                            <img src="/front_img/placeholders/screenshots/promo_2.png" alt="" class="img-responsive pull-left visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-200" style="max-width: 450px; margin-left: -130px;">
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Promo #2 -->

            <!-- Sign Up Action -->
            <section class="site-content site-section themed-background-dark">
                <div class="container">
                    <h2 class="site-heading text-center text-light" style="line-height:45px;">Use The Most Innovative Technology To Help Grow Your Revenue <br>To The Highest Potential <strong>Call: 1 (888) 508-5778</strong></h2>
                    <div class="site-block text-center">
                        <form action="/dashboardfront/contact" method="post" class="form-inline" onClick="/dashboardfront/contact">
                            <!--<div class="form-group">
                                <label class="sr-only" for="register-username">Username</label>
                                <input type="text" id="register-username" name="register-username" class="form-control input-lg" placeholder="Choose a username..">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="register-password">Password</label>
                                <input type="password" id="register-password" name="register-password" class="form-control input-lg" placeholder="..and a password!">
                            </div>-->
                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-success">Contact Us</button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
            <!-- END Sign Up Action -->

            <!-- Promo #3 -->
            <section class="site-section site-content border-bottom overflow-hidden">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 push">
                            <h2 class="site-heading"><strong>Patient Management</strong></h2>
                            <p class="feature-text text-muted push">Dental Plan Software manages your patients and plans with top of the line security and algorithms.  You will see all of your statistics of plans and patients all in one place.</p>
                            <h2 class="site-heading"><strong>Weekly Payouts</strong></h2>
                            <p class="feature-text text-muted">Receive your recurring revenue straight to your bank account every week.  Since we process billing of your dental plans, we make sure you receive your payout without any hiccups or third parties.</p>
                        </div>
                        <div class="col-sm-6 clearfix push">
                            <img src="/front_img/placeholders/screenshots/promo_3.png" alt="" class="img-responsive pull-right visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInLeft" data-element-offset="-200" style="max-width: 450px; margin-right: -130px;">
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Promo #3 -->
             <!-- Quick Stats -->
            <section class="site-content site-section themed-background-dark">
                <div class="container text-center">
                    <div class="row row-items">
                        <div class="col-sm-4">
                            <a href="/dashboardfront/features" class="feature visibility-none themed-background-success" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <i class="fa fa-check"></i>
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Easily Setup Patients</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">Dental Plan Software makes it simple for you to add your patients to your private dental plan.  You can even add family members of your patients and grow your revenue even more. </p>-->
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="features.html" class="feature visibility-none themed-background" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/dollar177.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Manage Your Fee Schedule</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">Specialists can create and manage their own fee schedule to stay competitive in the market.  Patients will be able to choose the specialist they like best according to fee schedule and profile.</p>-->
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <a href="dashboardfront/features" class="feature visibility-none themed-background-social" data-toggle="animation-appear" data-animation-class="animation-fadeInQuickInv" data-element-offset="-100">
                                <img src="/front_img/office.png" width="48" height="48"> 
                            </a>
                            <div class="visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInQuick2Inv" data-element-offset="-100">
                                <h4 class="site-heading feature-heading"><strong style="color:#fff;">Patient ID Cards</strong></h4>
                                <!--<p class="feature-text text-muted" style="text-align:center; color:#ebebeb">Dental Plan Software automatically emails your private dental plan ID cards to patients the moment you set them up for a plan. This gives you the professional look of an insurance company and gives the patient the warmth of being part of a trusted network.</p>-->
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- END Quick Stats -->
            <section class="site-section site-content border-bottom overflow-hidden">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-sm-push-6 push">
                            <h2 class="site-heading"><strong>Specialist Network</strong></h2>
                            <p class="feature-text text-muted push">Refer your patients to the top specialists in the Dental Plan Software network.  Specialists are hand chosen and the best in their field.</p>
                            <h2 class="site-heading"><strong>Receive Referrals</strong></h2>
                            <p class="feature-text text-muted">Specialists receive unlimited referrals from the dentists on the Dental Plan Software network.  High amount of referrals received electronically. Instantly.</p>
                        </div>
                        <div class="col-sm-6 col-sm-pull-6 clearfix push">
                            <img src="/front_img/placeholders/screenshots/promo_4.png" alt="" class="img-responsive pull-left visibility-none" data-toggle="animation-appear" data-animation-class="animation-fadeInRight" data-element-offset="-200" style="max-width: 450px; margin-left: -130px;">
                        </div>
                    </div>
                </div>
            </section>
            <!-- Testimonials -->
            <!--<section class="site-content site-section themed-background-muted">
                <div class="container">
                    <div id="testimonials-carousel" class="carousel slide carousel-html" data-ride="carousel" data-interval="4000">
                        <div class="carousel-inner text-center">
                            <div class="active item">
                                <blockquote>
                                    <p><img src="front_img/placeholders/avatars/avatar13@2x.jpg" alt="avatar" class="img-circle img-thumbnail img-thumbnail-avatar-2x"></p>
                                    <h3>A big thanks! Our web app looks great!</h3>
                                    <footer><em><strong>Maria Clark</strong>, http://example.com/</em></footer>
                                </blockquote>
                            </div>
                            <div class="item">
                                <blockquote>
                                    <p><img src="front_img/placeholders/avatars/avatar2@2x.jpg" alt="avatar" class="img-circle img-thumbnail img-thumbnail-avatar-2x"></p>
                                    <h3>It just works!</h3>
                                    <footer><em><strong>Roger Santos</strong>, http://example.com/</em></footer>
                                </blockquote>
                            </div>
                            <div class="item">
                                <blockquote>
                                    <p><img src="front_img/placeholders/avatars/avatar1@2x.jpg" alt="avatar" class="img-circle img-thumbnail img-thumbnail-avatar-2x"></p>
                                    <h3>A great product at a great price!</h3>
                                    <footer><em><strong>Edward Duncan</strong>, http://example.com/</em></footer>
                                </blockquote>
                            </div>
                            <div class="item">
                                <blockquote>
                                    <p><img src="front_img/placeholders/avatars/avatar7@2x.jpg" alt="avatar" class="img-circle img-thumbnail img-thumbnail-avatar-2x"></p>
                                    <h3>Awesome purchase, I'm so happy I made it!</h3>
                                    <footer><em><strong>Scott Gray</strong>, http://example.com/</em></footer>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </section>-->
            <!-- END Testimonials -->

            <!-- Footer -->
            <footer class="site-footer site-section site-section-light">
                <div class="container">
                    <!-- Footer Links -->
                    <div class="row">
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Company</h4>
                            <ul class="footer-nav ul-breath list-unstyled">
                                <li><a href="/dashboardfront/aboutus">About Us</a></li>
                                <li><a href="/dashboardfront/features">Features</a></li>
                                <li><a href="/dashboardfront/pricing">Pricing</a></li>
                                <li><a href="/dashboardfront/termscondition">Terms &amp; Conditions</a></li>
                                <li><a href="/dashboardfront/privacypolicy">Privacy Policy</a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Need support?</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="dashboardfront/contact"><i class="fa fa-fw fa-book"></i> Contact Us</a></li>
                            </ul>
                            <h4 class="footer-heading">We are social!</h4>
                            <ul class="footer-nav footer-nav-links list-inline">
                                <li><a href="javascript:void(0)" class="social-facebook" data-toggle="tooltip" title="Like our Facebook page"><i class="fa fa-fw fa-facebook"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-twitter" data-toggle="tooltip" title="Follow us on Twitter"><i class="fa fa-fw fa-twitter"></i></a></li>
                                <li><a href="javascript:void(0)" class="social-google-plus" data-toggle="tooltip" title="Like our Google+ page"><i class="fa fa-fw fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-sm-4">
                            <h4 class="footer-heading">Newsletter</h4>
                            <form action="/dashboardfront/suscribe" method="post" class="form-inline">
                                <div class="form-group">
                                    <label class="sr-only" for="register-email">Your Email</label>
                                    <div class="input-group">
                                        <input type="email" id="register-email" name="register-email" class="form-control" placeholder="Your Email..">
                                        <span class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Subscribe</button>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <h4 class="footer-heading"><a href="/dashboardfront/contact" style="color:#FFC">Check Demo</a></h4>
                            &copy; <em>2016</em> Crafted with <i class="fa fa-heart text-danger"></i> by <a href="http://docmate.com/" style="color:#FFC">A1 Healthcare Technologies</a>
                        </div>
                    </div>
                    <!-- END Footer Links -->
                </div>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in front_js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-arrow-up"></i></a>

        <!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
        <script src="/front_js/vendor/jquery-2.1.4.min.js"></script>
        <script src="/front_js/vendor/bootstrap.min.js"></script>
        <script src="/front_js/plugins.js"></script>
        <script src="/front_js/app.js"></script>
    </body>
</html>
