<?php
// plan type
$plan_type[1] = 'Individual';
$plan_type[2] = 'Family';
$plan_type[3] = 'Addon';

// plan cycle
$plan_billing_cycle[1] = 'Monthly';
$plan_billing_cycle[2] = 'Annually';

?>

<!-- Page content -->
<div id="page-content">
    <!-- Pricing Tables Header -->
    <div class="content-header">
        <div class="row">
            <div class="col-sm-6">
                <div class="header-section">
                    <h1>Choose Plan</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- END Pricing Tables Header -->

    <!-- Normal Pricing Tables Block -->
    <div class="block">

        <!-- Normal Pricing Tables Content -->
        <div class="row">
<?php // plan query
foreach($listplans as $planslistingvalue) {
?>
            <div class="col-sm-3">
                <table class="table table-borderless table-pricing">
                <thead>
                    <tr>
                    <th><?php echo $planslistingvalue['plan_name'];?><br /><small><?php echo $planslistingvalue['heading_line'];?></small></th>
                   </tr>
                    </thead>
                    <tbody>
                        <tr class="active">
                            <td>
<table width="100%" border="0">
  <tr>
    <td colspan="2"><?php echo $plan_type[1];?></td>
  </tr>
  <tr>
    <td><?php if($planslistingvalue['plan_monthly_price']) { ?>
<strong><?php echo "$".$planslistingvalue['plan_monthly_price'];?></strong><br><small><?php echo $plan_billing_cycle[1];?></small>
<?php } ?>
</td>
    <td><?php if($planslistingvalue['plan_yearly_price']) { ?>
<strong><?php echo "$".$planslistingvalue['plan_yearly_price'];?></strong><br><small><?php echo $plan_billing_cycle[2];?></small>
<?php } ?></td>
  </tr>
  <tr>
    <td colspan="2"><?php echo $plan_type[3];?></td>
  </tr>
  <tr>
    <td><?php if($planslistingvalue['addon_monthly_price']) { ?>
<strong><?php echo "$".$planslistingvalue['addon_monthly_price'];?></strong><br><small><?php echo $plan_billing_cycle[1];?></small>
<?php } ?>
</td>
    <td><?php if($planslistingvalue['addon_monthly_price']) { ?>
<strong><?php echo "$".$planslistingvalue['addon_yearly_price'];?></strong><br><small><?php echo $plan_billing_cycle[2];?></small>
<?php } ?></td>
  </tr>
</table>

                                <!--<h1>-->

<!--</h1>-->
                            </td>
                        </tr>
                        <tr>
                            <td align="left">

 <?php 
foreach($listplanservice as $listplanservicevalue) {
   if($listplanservicevalue['plan_id']==$planslistingvalue['plan_id']){
            echo '<b>'.$listplanservicevalue['service_type'].'</b><br/>';
              }
      }
?>                           
</td>
                        </tr>
                        <tr class="active">
                            <td>
                                <a href="/dashboardfront/planselection/<?php echo $planslistingvalue['plan_id'];?>" class="btn btn-effect-ripple  btn-success"><i class="fa fa-arrow-right"></i> Detail View</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
<?php } ?>
            
        </div>
        <!-- END Normal Pricing Tables Content -->
    </div>
    <!-- END Normal Pricing Tables Block -->
</div>
<!-- END Page Content -->