               <!-- Main Sidebar -->
<div id="sidebar">
    <!-- Sidebar Brand -->
    <div id="sidebar-brand" class="themed-background">
        <a href="/dashboardfront/welcome" class="sidebar-title">
           <img src="/img/logo.png" align="Dental Plan" width="100%" height="100%" /><!-- <i class="fa fa-cube"></i> <span class="sidebar-nav-mini-hide">Dental Plan</span>-->
        </a>
    </div>
    <!-- END Sidebar Brand -->

    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
                        <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                                                <li>
                    <a href="home.php" class=" active"><i class="gi gi-compass sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
                                    </li>
                                                                <li class="sidebar-separator">
                    <i class="fa fa-ellipsis-h"></i>
                </li>
                                                                <li>
                    <a href="list_refered.php"><i class="gi gi-airplane sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Referrals</span></a>
                                    </li>
                                                                <li>
                    <a href="spl_patients.php"><i class="fa fa-rocket sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Patients</span></a>
                                    </li>
                                                                <li>
                    <a href="spl_cc_pay.php"><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Billing Information</span></a>
                                    </li>
                                                                <li>
                    <a href="specialist_edit.php"><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">My Account</span></a>
                                    </li>
                                                                <li>
                    <a href="/dashboardfront/splservices"><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Manage Fee Schedule</span></a>
                                    </li>
                                                                <li>
                    <a href="/dashboardfront/doctorsupport"><i class="gi gi-star sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Support</span></a>
                                    </li>
                                            </ul>
            <!-- END Sidebar Navigation -->
                    </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->


</div>
<!-- END Main Sidebar -->